# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded math 1.2.5 [list source [file join $dir math/math.tcl]]
package ifneeded math::bigfloat 1.2.2 [list source [file join $dir math/bigfloat.tcl]]
package ifneeded math::bigfloat 2.0.1 [list source [file join $dir math/bigfloat2.tcl]]
package ifneeded math::bignum 3.1.1 [list source [file join $dir math/bignum.tcl]]
package ifneeded math::complexnumbers 1.0.2 [list source [file join $dir math/qcomplex.tcl]]
package ifneeded math::constants 1.0.1 [list source [file join $dir math/constants.tcl]]
package ifneeded math::fourier 1.0.2 [list source [file join $dir math/fourier.tcl]]
package ifneeded math::fuzzy 0.2 [list source [file join $dir math/fuzzy.tcl]]
package ifneeded math::geometry 1.0.4 [list source [file join $dir math/geometry.tcl]]
package ifneeded math::interpolate 1.0.3 [list source [file join $dir math/interpolate.tcl]]
package ifneeded math::linearalgebra 1.1.3 [list source [file join $dir math/linalg.tcl]]
package ifneeded math::machineparameters 0.1 [list source [file join $dir math/machineparameters.tcl]]
package ifneeded math::optimize 1.0 [list source [file join $dir math/optimize.tcl]]
package ifneeded math::polynomials 1.0.1 [list source [file join $dir math/polynomials.tcl]]
package ifneeded math::roman 1.0 [list source [file join $dir math/romannumerals.tcl]]
package ifneeded opt 1.0 [list source [file join $dir opt.tcl]]
package ifneeded optimization 1.0 [list source [file join $dir optimization1.0/optimization.tcl]]
